export const CONTENT_TYPES = {
  EXTERNAL_LINK: 'EXTERNAL_LINK',
  HEADING: 'HEADING',
  HTML: 'HTML',
  GEO: 'GEO',
  GRID: 'GRID',
  INTERNAL_LINK: 'INTERNAL_LINK',
  IMAGE: 'IMAGE',
  LIST: 'LIST'
};

export const CATEGORIES = {
  NORTH_AMERICA: 'NORTH_AMERICA'
};
